name: Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./amnis-process

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
      working-directory: ./
      with:
        path: main

    - name: Checkout Amnis State
      uses: actions/checkout@v3
      working-directory: ./
      with:
        repository: amnis-dev/amnis-state.git
        ref: main
        path: amnis-state

    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup NodeJS with PNPM Caching
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install NodeJS Dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint for Code-Style Errors
      run: pnpm lint

    - name: Run Unit Tests
      run: pnpm test

    - name: Run Build
      run: pnpm build